language: objective-c
xcode_workspace: Carthage.xcworkspace
xcode_scheme: carthage
osx_image: xcode7.2
before_install:
  - brew install bats
  - make install
install: true
git:
  submodules: false
script: BUILD_TOOL=xctool script/cibuild
